# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='notes_review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
